### PR TITLE
Fix RemoveMappersFix by using SafeDeleteFix

### PR DESCRIPTION
**Pull request by hduelme**
@filiphr I found a working solution for #155 
I used the `SafeDeleteFix` to delete the instance unlike my solution in #176 it checks for usage.

### CODE REVIEW

**Review by filiphr — COMMENTED** [review]
This is amazing @hduelme. Such a simple fix 😄. Thanks a lot for figuring this out.

One small thing, I think that the changes with the lists are not needed anymore. I don't think that `createRemoveMappersFix` will ever really return `null`. The failure that was visible in #162 is due to some other mistake with the reflection that I had done.  I believe that the only change should be to extend from `SafeDeleteFix` and that's it. What do you think?

**Comment by hduelme** [comment]
@filiphr the null return of `createRemoveMappersFix` could still happen.
For example: 
```
@Mapper(componentModel = "spring")
abstract class WrongComponentModelMapper {

    static {
        Mappers.getMapper(WrongComponentModelMapper.class);
    }
    
    Target map(Target source);
}
```
or
```
@Mapper(config = MyConfig.class, componentModel = "spring")
interface WrongComponentModelMapper {


    WrongComponentModelMapper INSTANCE = () -> {
        return Mappers.getMapper(WrongComponentModelMapper.class);
    };

    Target map(Target source);
}
```
No variable to delete but the inspection still shows up.
Or while typing. This would cause a plugin crash if we don't check.

Alternatively we could change the behavior to always return the delete Option.

**Comment by hduelme** [comment]
@filiphr Yes, we should solve it step by step. There should be no possible crashes in this version. So I would leaf it as it is for now. Would you open a issue for step 2?

**Comment by filiphr** [comment]
> Would you open a issue for step 2?


Yup, I've opened #183 for this.

I'll proceed with merging this one

**Pull request merged**
