### PR TITLE
#16 autocomplete for public fields

### PR DESCRIPTION
**Pull request by thunderhook**
Implemented the auto-completion for targets with public non-static non-final fields.
The source auto-completion works with any public field.

Sadly there weren't any tests for completion, so I couldn't provide additional tests.

### CODE REVIEW

**Comment by thunderhook** [comment]
Any idea why the tests aren't working? They work locally.

**Comment by filiphr** [comment]
@thunderhook seems like they are only failing on the LATEST-EAP-SNAPSHOT. I will allow failures on the latest 😄. 

Had a quick glance over the PR and it looks OK. I think that I have some tests locally (I was looking into doing this as well).

**Comment by filiphr** [comment]
@thunderhook I've done some fixes on master so the build can work with the LATEST_EAP_SNAPSHOT as well. 

You can have a look at https://github.com/mapstruct/mapstruct-idea/commit/01785989a59059181b9b2d2ec2570da77587a484 (a branch where I was trying out public fields). There are some data fixture prepared in there. Will you be able to add some tests with those fixtures? The tests are more or less the same as the getters / setters.

**Comment by thunderhook** [comment]
I hope I have rebased correctly. I've added the fixture tests - please have a look.

**Comment by filiphr** [comment]
@thunderhook I think that something went wrong with the rebase. I am seeing commits and changes from master here. Can you try again perhaps? You can also create a new branch and aoply your commits there. You can then force push that local branch to the branch 9f this commit. This way the PR will be properly updated.

Thanks

**Comment by thunderhook** [comment]
@filiphr I am sorry, this whole pull request is a mess. 💣 The tests worked fine (locally) before I did this catastrophical "kind of" rebase. Am I even helping or do I cause more trouble by further commiting? 😃 Please, just tell me if I should stop contributing.

**Comment by torsten-github** [comment]
Any progress on this. Waiting for support via public fields (without getter/setter)

**Comment by filiphr** [comment]
This has slipped through. I am sorry @thunderhook. 

>Am I even helping or do I cause more trouble by further commiting? 😃 Please, just tell me if I should stop contributing.

Contributing is always helping out. You should never stop 😄. 

>Any progress on this. Waiting for support via public fields (without getter/setter)

I'll try to merge this PR this week.

**Comment by filiphr** [comment]
And I managed to this this today. Part of PR https://github.com/mapstruct/mapstruct-idea/pull/40. @thunderhook I kept your commit with your name as well. Thanks a lot and sorry for taking me so much time to merge it

**Pull request closed without merging**
