### PR TITLE
add idea 2024.1 to build matrix

### PR DESCRIPTION
**Pull request by hduelme**
Added latest released version to build matrix

### CODE REVIEW

**Comment by hduelme** [comment]
I also update c`odecov/codecov-action` to v3. The old version failed to upload.

**Comment by thunderhook** [comment]
@hduelme Thanks.

Interestingly now v3 seems to fail when uploading it. Any idea why that happens?

**Comment by hduelme** [comment]
@thunderhook yes it's a known issue of codecov see [https://github.com/codecov/codecov-action/issues/598](https://github.com/codecov/codecov-action/issues/598)

Seems like they published a [v4](https://github.com/codecov/codecov-action/releases/tag/v4.0.0)  to address this issue.

**Comment by hduelme** [comment]
One thing to not is that tokenless uploading is no longer supported in v4. If the project currently doesn't have a token see [https://docs.codecov.com/docs/adding-the-codecov-token#github-actions](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions)

**Comment by thunderhook** [comment]
Thanks @hduelme 

I will merge this for now. @filiphr have a look at what @hduelme [wrote](https://github.com/mapstruct/mapstruct-idea/pull/189#issuecomment-2068018662) about the codecov token.
I don't know if you have anything to do with it.

**Comment by thunderhook** [comment]
OK, next time I'll leave the merge to you @filiphr 😅 

Pipeline looked good (see details above) and everything went fine:
* https://github.com/mapstruct/mapstruct-idea/actions/runs/8772442268/job/24071389310

The main branch can't upload the coverage report now due to the missing token:
* https://github.com/mapstruct/mapstruct-idea/actions/runs/8774747414/job/24076270436

So we'll have to add a token now.

**Comment by filiphr** [comment]
@thunderhook I've added the token in 4fa44fbeadb303c9f458d8449433bfa267e71a57. However, it seems like the coverage is now 0 (https://app.codecov.io/github/mapstruct/mapstruct-idea). Perhaps something is not correct with what Jacoco generates

**Pull request merged**
