### PR TITLE
#20 Kotlin support

### PR DESCRIPTION
**Pull request by ifrankwang**
After a few weeks of effort, I finally got it to work!

### CODE REVIEW

**Comment by filiphr** [comment]
Thanks a lot for the contribution @ifrankwang. I am going on holiday tomorrow, so I would be able to review this once I am back in 2 weeks.

One thing I noticed is that we now have a mandatory dependency on the Kotlin plugin. We shouldn't do that. Can you please make that dependency optional? Have a look at [this](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_dependencies.html#optional-plugin-dependencies) for how to do it.

**Comment by ifrankwang** [comment]
ok, working on it.

**Comment by ifrankwang** [comment]
Hi @filiphr, I've made kotlin as an optional plugin. Would you check on it in your spare time?

**Comment by filiphr** [comment]
Hey @ifrankwang, thanks a lot for your patience. I finally managed to test and review this PR. 

I had to do some polishing in order for it to work without problems when the Kotlin plugin is not enabled. It was not working before due to the usage of `MapStructUtilKt` in the `BaseReference`. I adapted this to only be used for Kotlil String Templates.

I also removed the `KtMapstructElementUtil` and replaced it with the `MapStructKotlinElementUtils`. I was having troubles following the logic in `KtMapstructElementUtil` due to my lack of Kotlin knowledge most likely. I tried to create some pattern utils similar to the `PsiJavaPatterns` and hopefully it would be easier for me to maintain this 😄.

You can have a look at my changes in https://github.com/mapstruct/mapstruct-idea/commit/4b847369dc1d09504f281edfe2af3a7957dba010.

If you are OK with them then I am going to go and merge this and create a new release.

By the way, do you know why did you need to add the `properties` plugin?

**Comment by ifrankwang** [comment]
> If you are OK with them then I am going to go and merge this and create a new release.

OK, go ahead.

> By the way, do you know why did you need to add the properties plugin?

Because I got some compile error when missing this plugin.

**Comment by filiphr** [comment]
Manually merged in https://github.com/mapstruct/mapstruct-idea/commit/41dd19040264c64effb63b5148fc462da791af0c and polish in https://github.com/mapstruct/mapstruct-idea/commit/1119db7cdb94d088e7e0ed59b7ac36e7ae9e757f

**Pull request closed without merging**
