### PR TITLE
#155 Fix RemoveMappersFix to use new 2023.3 RemoveUnusedVariableFix intention action

### PR DESCRIPTION
**Pull request by filiphr**

### CODE REVIEW

**Comment by filiphr** [comment]
I've also submitted https://github.com/JetBrains/intellij-community/pull/2617 in case the IntelliJ team agrees in keeping the `getText` so that we can use it. Otherwise, we would remove that particular fix until we make 2023.3 the lowest version we support

**Review by thunderhook — APPROVED** [review]
Sounds good. Approved the pull request.
Feel free to merge it if you know more about the intellij issue.

**Comment by filiphr** [comment]
I'll wait a bit to see what the IntelliJ teams says. If they agree with it then I'll finish this one with that in mind. Otherwise, I'll need to do alternative.

**Comment by filiphr** [comment]
Closing this in favor of the way better solution by @hduelme  in #179

**Pull request closed without merging**
